<a href="https://colab.research.google.com/github/Reshmatr2407/Python/blob/python/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import pandas as pd

In [4]:
arr=np.arange(1,21)
print(arr)
arr.shape
arr.reshape(4,5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [8]:
arr2=np.zeros(10)
print(arr2)
arr2[4]=100
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  0.   0.   0.   0. 100.   0.   0.   0.   0.   0.]


In [9]:
arr3=np.arange(2,41,2)
print(arr3)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [19]:
arr4=np.random.randint(1,100,size=15)
print(arr4)
print(arr4.min())
print(arr4.max())
print(arr4.mean())
print(arr4.std())

[80 90 63 74  9 61 77  1 62 42 50 33 56 84 41]
1
90
54.86666666666667
25.28732664575061


In [26]:
sales =np.array([1000,2000,3000])
costs=np.array([100,200,300])
profit=sales-costs
print(profit)
profit_per=(profit / costs) * 100

[ 900 1800 2700]


In [54]:
arr5 = np.random.randint(1, 100, size=36)
arr5 = arr5.reshape(6, 6)
print("Reshaped Array (6x6):")
print(arr5)

col_sum = np.sum(arr5, axis=0)
print("Column Sums:", col_sum)
row_sum = np.sum(arr5, axis=1)
print("Row Sums:", row_sum)
tot_sum = np.sum(arr5)
print("Total Sum:", tot_sum)

Reshaped Array (6x6):
[[73 15 50 75 65 48]
 [55 30 41 25 81 69]
 [63 51  7 81 86 72]
 [28 77 26 97 42 37]
 [45 75 37 96 14  4]
 [88 23 25 65 94 64]]
Column Sums: [352 271 186 439 382 294]
Row Sums: [326 301 360 307 271 359]
Total Sum: 1924


Reshaped Array (4x5):
[[14 62 65 36 52]
 [68 26 30 37 53]
 [36 54 25 82 31]
 [80 37 80 31 28]]
Column Sums: [198 179 200 186 164]
Row Sums: [229 214 228 256]
Total Sum: 927


In [60]:

stock_prices = np.array([100,102,98,105])
print("Stock Prices:")
print(stock_prices)
previous_prices = np.roll(stock_prices, 1)
print("Previous Prices:")
print(previous_prices)
daily_returns = (stock_prices - previous_prices) / previous_prices
print("Daily Returns:")
print(daily_returns)
# Set the first return to NaN since there's no previous price for the first day
daily_returns[0] = np.nan
print("Daily Returns:")
print(daily_returns)


Stock Prices:
[100 102  98 105]
Previous Prices:
[105 100 102  98]
Daily Returns:
[-0.04761905  0.02       -0.03921569  0.07142857]
Daily Returns:
[        nan  0.02       -0.03921569  0.07142857]


In [63]:

annual_rates = np.array([0.05, 0.06, 0.07])
monthly_rates = (1 + annual_rates) ** (1/12) - 1
print("Monthly Rates:")
print(monthly_rates)


Monthly Rates:
[0.00407412 0.00486755 0.00565415]


In [66]:
weights = np.array([0.2, 0.5, 0.3])
print("Weights:")
print(weights)
print("Sum of Weights:", np.sum(weights))
normalized_weights = weights / np.sum(weights)

# Print the normalized weights
print("Normalized Weights:")
print(normalized_weights)
print("Sum of Normalized Weights:", np.sum(normalized_weights))

Weights:
[0.2 0.5 0.3]
Sum of Weights: 1.0
Normalized Weights:
[0.2 0.5 0.3]
Sum of Normalized Weights: 1.0


In [76]:

data=[1200, 1500, 1800, 2000, 2200]
series=pd.Series(data)
min_val=series.min()
max_val=series.max()
# index_max=series.idmax()
index_of_max = series.idxmax()

print("Minimum Value:", min_val)
print("Maximum Value:", max_val)
# print("Index of Maximum Value:", index_max)
print("Index of Max Value:", index_of_max)

Minimum Value: 1200
Maximum Value: 2200
Index of Max Value: 4


In [93]:


# Step 2: Create a DataFrame with student names and marks
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math': [85,90,78,88],
    'Science': [92,85,80,95],
    'English': [88,76,90,84]
}

df = pd.DataFrame(data)
print(df)

# Step 3: Print only the Math column
print("Math Column:")
print(df['Math'])

# Print the first 2 rows
print("\nFirst 2 Rows:")
print(df.head(2))

# Print the shape of the DataFrame
print("\nShape of DataFrame:")
print(df.shape)


      Name  Math  Science  English
0    Alice    85       92       88
1      Bob    90       85       76
2  Charlie    78       80       90
3    David    88       95       84
Math Column:
0    85
1    90
2    78
3    88
Name: Math, dtype: int64

First 2 Rows:
    Name  Math  Science  English
0  Alice    85       92       88
1    Bob    90       85       76

Shape of DataFrame:
(4, 4)


In [94]:

data1={
     "Account": [101,102,103,104],
    "Balance": [5000,15000,7000,12000]
}
# Create the DataFrame
df = pd.DataFrame(data1)
print(df)
# Filter rows where Balance > 8000
filtered_df1 = df[df["Balance"] > 8000]

# Filter rows where Balance is between 6000 and 13000
filtered_df2 = df[(df["Balance"] >= 6000) & (df["Balance"] <= 13000)]
print("Rows where Balance > 8000:")
print(filtered_df1)

print("\nRows where Balance is between 6000 and 13000:")
print(filtered_df2)



   Account  Balance
0      101     5000
1      102    15000
2      103     7000
3      104    12000
Rows where Balance > 8000:
   Account  Balance
1      102    15000
3      104    12000

Rows where Balance is between 6000 and 13000:
   Account  Balance
2      103     7000
3      104    12000
